### ISSUE TITLE
Add Timeline to Challenge section

### ISSUE THREAD

**Issue by chadmartin** [globalresiliencepartnership/globalresiliencepartnership.github.io#28]
Dear DevSeed Team:

Will you please add the timeline visual (from Page 7 of the source document, "GRP_Guideline...") to the table in the Challenge section titled "GLOBAL RESILIENCE CHALLENGE UPDATE"?

Please let us know if you have questions.

Thanks!
Chad

**Comment by chadmartin** [comment]
Happy New Year!

Any updates? We need this ASAP.

Thanks!
-Chad

**Comment by smit1678** [comment]
Closing this conversation for now. Will pick up as we finalize other aspects of the website.
